# Step 1 - Load clean dataset

In [6]:
import pandas as pd

In [7]:
df = pd.read_csv("car_dataset.csv")

In [25]:
df

    car_id                  name         brand  category  pricePerDay
0        1       Toyota Fortuner        Toyota       SUV           85
1        2            Honda CR-V         Honda       SUV           75
2        3         Ford Explorer          Ford       SUV           90
3        4        Hyundai Tucson       Hyundai       SUV           70
4        5          Kia Sportage           Kia       SUV           68
5        6         Nissan Patrol        Nissan       SUV          110
6        7     Mitsubishi Pajero    Mitsubishi       SUV           95
7        8   Land Rover Defender    Land Rover       SUV          150
8        9         Jeep Wrangler          Jeep       SUV          105
9       10                BMW X5           BMW       SUV          180
10      11         Tesla Model 3         Tesla  Electric          120
11      12         Tesla Model Y         Tesla  Electric          140
12      13         Tesla Model S         Tesla  Electric          200
13      14           Nissan Leaf        Nissan  Electric           75
14      15                BMW i4           BMW  Electric          165
15      16           Audi e-tron          Audi  Electric          175
16      17       Hyundai Ioniq 5       Hyundai  Electric          110
17      18               Kia EV6           Kia  Electric          105
18      19        Porsche Taycan       Porsche  Electric          280
19      20          Mercedes EQS      Mercedes  Electric          260
20      21      Lamborghini Urus   Lamborghini    Luxury          500
21      22     Rolls Royce Ghost   Rolls Royce    Luxury          900
22      23   Bentley Continental       Bentley    Luxury          750
23      24      Mercedes S-Class      Mercedes    Luxury          350
24      25          BMW 7 Series           BMW    Luxury          320
25      26               Audi A8          Audi    Luxury          300
26      27      Porsche Panamera       Porsche    Luxury          400
27      28       Maserati Ghibli      Maserati    Luxury          380
28      29          Ferrari Roma       Ferrari    Luxury         1200
29      30   Lamborghini Huracan   Lamborghini    Luxury         1100
30      31      Mazda MX-5 Miata         Mazda  2-Seater           95
31      32           Porsche 911       Porsche  2-Seater          550
32      33                BMW Z4           BMW  2-Seater          220
33      34          Mercedes SLC      Mercedes  2-Seater          210
34      35               Audi TT          Audi  2-Seater          190
35      36           Honda S2000         Honda  2-Seater          130
36      37           Toyota GR86        Toyota  2-Seater          115
37      38            Subaru BRZ        Subaru  2-Seater          110
38      39          Ford Mustang          Ford  2-Seater          175
39      40    Chevrolet Corvette     Chevrolet  2-Seater          450
40      41           Toyota RAV4        Toyota       SUV           72
41      42           Honda Pilot         Honda       SUV           88
42      43       Chevrolet Tahoe     Chevrolet       SUV          120
43      44            Rivian R1T        Rivian  Electric          195
44      45       Volkswagen ID.4    Volkswagen  Electric           98
45      46  Rolls Royce Cullinan   Rolls Royce    Luxury         1000
46      47     Aston Martin DB11  Aston Martin    Luxury          850
47      48           Lotus Elise         Lotus  2-Seater          160
48      49           Alpine A110        Alpine  2-Seater          145
49      50           Dodge Viper         Dodge  2-Seater          380

# Step 2 - Category Encoding

In [9]:
from sklearn.preprocessing import OneHotEncoder

In [10]:
encoder = OneHotEncoder()

In [12]:
category_encoding = encoder.fit_transform(df[["category"]]).toarray()

In [13]:
print(category_encoding)

[[0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]]

# Step 3 - Price Normalization

In [14]:
from sklearn.preprocessing import MinMaxScaler

In [15]:
scale = MinMaxScaler()

In [19]:
price_scale = scale.fit_transform(df[["pricePerDay"]])

In [20]:
print(price_scale)

[[0.01501767]
 [0.00618375]
 [0.01943463]
 [0.00176678]
 [0.        ]
 [0.03710247]
 [0.02385159]
 [0.07243816]
 [0.03268551]
 [0.09893993]
 [0.0459364 ]
 [0.06360424]
 [0.11660777]
 [0.00618375]
 [0.08568905]
 [0.09452297]
 [0.03710247]
 [0.03268551]
 [0.18727915]
 [0.16961131]
 [0.38162544]
 [0.73498233]
 [0.6024735 ]
 [0.24911661]
 [0.22261484]
 [0.204947  ]
 [0.29328622]
 [0.27561837]
 [1.        ]
 [0.91166078]
 [0.02385159]
 [0.42579505]
 [0.13427562]
 [0.1254417 ]
 [0.10777385]
 [0.05477032]
 [0.04151943]
 [0.03710247]
 [0.09452297]
 [0.33745583]
 [0.00353357]
 [0.01766784]
 [0.0459364 ]
 [0.11219081]
 [0.02650177]
 [0.82332155]
 [0.69081272]
 [0.08127208]
 [0.0680212 ]
 [0.27561837]]

# Step 4 - Feature Matrix

In [21]:
import numpy as np

In [22]:
feature_matrix = np.hstack([category_encoding , price_scale])

In [23]:
print(feature_matrix.shape)

(50, 5)

In [24]:
print(feature_matrix)

[[0.         0.         0.         1.         0.01501767]
 [0.         0.         0.         1.         0.00618375]
 [0.         0.         0.         1.         0.01943463]
 [0.         0.         0.         1.         0.00176678]
 [0.         0.         0.         1.         0.        ]
 [0.         0.         0.         1.         0.03710247]
 [0.         0.         0.         1.         0.02385159]
 [0.         0.         0.         1.         0.07243816]
 [0.         0.         0.         1.         0.03268551]
 [0.         0.         0.         1.         0.09893993]
 [0.         1.         0.         0.         0.0459364 ]
 [0.         1.         0.         0.         0.06360424]
 [0.         1.         0.         0.         0.11660777]
 [0.         1.         0.         0.         0.00618375]
 [0.         1.         0.         0.         0.08568905]
 [0.         1.         0.         0.         0.09452297]
 [0.         1.         0.         0.         0.03710247]
 [0.         1.         0.         0.         0.03268551]
 [0.         1.         0.         0.         0.18727915]
 [0.         1.         0.         0.         0.16961131]
 [0.         0.         1.         0.         0.38162544]
 [0.         0.         1.         0.         0.73498233]
 [0.         0.         1.         0.         0.6024735 ]
 [0.         0.         1.         0.         0.24911661]
 [0.         0.         1.         0.         0.22261484]
 [0.         0.         1.         0.         0.204947  ]
 [0.         0.         1.         0.         0.29328622]
 [0.         0.         1.         0.         0.27561837]
 [0.         0.         1.         0.         1.        ]
 [0.         0.         1.         0.         0.91166078]
 [1.         0.         0.         0.         0.02385159]
 [1.         0.         0.         0.         0.42579505]
 [1.         0.         0.         0.         0.13427562]
 [1.         0.         0.         0.         0.1254417 ]
 [1.         0.         0.         0.         0.10777385]
 [1.         0.         0.         0.         0.05477032]
 [1.         0.         0.         0.         0.04151943]
 [1.         0.         0.         0.         0.03710247]
 [1.         0.         0.         0.         0.09452297]
 [1.         0.         0.         0.         0.33745583]
 [0.         0.         0.         1.         0.00353357]
 [0.         0.         0.         1.         0.01766784]
 [0.         0.         0.         1.         0.0459364 ]
 [0.         1.         0.         0.         0.11219081]
 [0.         1.         0.         0.         0.02650177]
 [0.         0.         1.         0.         0.82332155]
 [0.         0.         1.         0.         0.69081272]
 [1.         0.         0.         0.         0.08127208]
 [1.         0.         0.         0.         0.0680212 ]
 [1.         0.         0.         0.         0.27561837]]

# Save all

In [26]:
feature_df = pd.DataFrame(feature_matrix , columns=['2-Seater', 'Electric','Luxury', 'SUV', 'price_scaled'])

In [27]:
feature_df['car_id'] = df['car_id'].values
feature_df['name'] = df['name'].values

In [29]:
feature_df.to_csv("feature_matrix.csv", index=False)

In [32]:
feature_df

    2-Seater  Electric  Luxury  SUV  price_scaled  car_id                  name
0        0.0       0.0     0.0  1.0      0.015018       1       Toyota Fortuner
1        0.0       0.0     0.0  1.0      0.006184       2            Honda CR-V
2        0.0       0.0     0.0  1.0      0.019435       3         Ford Explorer
3        0.0       0.0     0.0  1.0      0.001767       4        Hyundai Tucson
4        0.0       0.0     0.0  1.0      0.000000       5          Kia Sportage
5        0.0       0.0     0.0  1.0      0.037102       6         Nissan Patrol
6        0.0       0.0     0.0  1.0      0.023852       7     Mitsubishi Pajero
7        0.0       0.0     0.0  1.0      0.072438       8   Land Rover Defender
8        0.0       0.0     0.0  1.0      0.032686       9         Jeep Wrangler
9        0.0       0.0     0.0  1.0      0.098940      10                BMW X5
10       0.0       1.0     0.0  0.0      0.045936      11         Tesla Model 3
11       0.0       1.0     0.0  0.0      0.063604      12         Tesla Model Y
12       0.0       1.0     0.0  0.0      0.116608      13         Tesla Model S
13       0.0       1.0     0.0  0.0      0.006184      14           Nissan Leaf
14       0.0       1.0     0.0  0.0      0.085689      15                BMW i4
15       0.0       1.0     0.0  0.0      0.094523      16           Audi e-tron
16       0.0       1.0     0.0  0.0      0.037102      17       Hyundai Ioniq 5
17       0.0       1.0     0.0  0.0      0.032686      18               Kia EV6
18       0.0       1.0     0.0  0.0      0.187279      19        Porsche Taycan
19       0.0       1.0     0.0  0.0      0.169611      20          Mercedes EQS
20       0.0       0.0     1.0  0.0      0.381625      21      Lamborghini Urus
21       0.0       0.0     1.0  0.0      0.734982      22     Rolls Royce Ghost
22       0.0       0.0     1.0  0.0      0.602473      23   Bentley Continental
23       0.0       0.0     1.0  0.0      0.249117      24      Mercedes S-Class
24       0.0       0.0     1.0  0.0      0.222615      25          BMW 7 Series
25       0.0       0.0     1.0  0.0      0.204947      26               Audi A8
26       0.0       0.0     1.0  0.0      0.293286      27      Porsche Panamera
27       0.0       0.0     1.0  0.0      0.275618      28       Maserati Ghibli
28       0.0       0.0     1.0  0.0      1.000000      29          Ferrari Roma
29       0.0       0.0     1.0  0.0      0.911661      30   Lamborghini Huracan
30       1.0       0.0     0.0  0.0      0.023852      31      Mazda MX-5 Miata
31       1.0       0.0     0.0  0.0      0.425795      32           Porsche 911
32       1.0       0.0     0.0  0.0      0.134276      33                BMW Z4
33       1.0       0.0     0.0  0.0      0.125442      34          Mercedes SLC
34       1.0       0.0     0.0  0.0      0.107774      35               Audi TT
35       1.0       0.0     0.0  0.0      0.054770      36           Honda S2000
36       1.0       0.0     0.0  0.0      0.041519      37           Toyota GR86
37       1.0       0.0     0.0  0.0      0.037102      38            Subaru BRZ
38       1.0       0.0     0.0  0.0      0.094523      39          Ford Mustang
39       1.0       0.0     0.0  0.0      0.337456      40    Chevrolet Corvette
40       0.0       0.0     0.0  1.0      0.003534      41           Toyota RAV4
41       0.0       0.0     0.0  1.0      0.017668      42           Honda Pilot
42       0.0       0.0     0.0  1.0      0.045936      43       Chevrolet Tahoe
43       0.0       1.0     0.0  0.0      0.112191      44            Rivian R1T
44       0.0       1.0     0.0  0.0      0.026502      45       Volkswagen ID.4
45       0.0       0.0     1.0  0.0      0.823322      46  Rolls Royce Cullinan
46       0.0       0.0     1.0  0.0      0.690813      47     Aston Martin DB11
47       1.0       0.0     0.0  0.0      0.081272      48           Lotus Elise
48       1.0       0.0     0.0  0.0      0.068021      49           Alpine A110
49       1.0       0.0     0.0  0.0      0.275618      50           Dodge Viper